### PR TITLE
mongo: escape special characters in uri

### PR DESCRIPTION
**Pull request by ganeshi4u**
usernames and passwords might contain special characters which needs to be parsed in order to escape.

`InvalidURI: ':' or '@' characters in a username or password must be escaped according to RFC 2396.`

### CODE REVIEW

**Comment by baalajimaestro** [comment]
So many force-pushes, test locally before pushing

**Comment by ganeshi4u** [comment]
Am not sure on what could be wrong here. I have my bot running fine locally without any issues. I have also added the null checks just in case.

Anyway does the CI build env here have a working config? because i have introduced a few new variables and the conditions depend on it.

**Comment by baalajimaestro** [comment]
@ganeshi4u Its does posses a proper working config as you can see all the other commits have CI passed status.

**Comment by ganeshi4u** [comment]
@baalajimaestro alright i was able to reproduce the issue, like i said it's due to the missing of new config variables that i have introduced with this commit. These variables need to be present in your CI config accordingly in order to work. I can't think of any other way around to simply this even more, but this sure is an issue while usernames and passwords contain special characters which in my case i do and MongoClient fails to establish a connection resulting in a crash!

**Comment by raphielscape** [comment]
This has a new config variables, testing should happen locally, we need more broader testing

**Comment by baalajimaestro** [comment]
I'll review it locally when I can.

**Comment by kandnub** [comment]
> _Usernames can only contain ASCII letters, numbers, hyphens, and underscores, and should begin with a letter or number._

Said so when you try to create an invalid username for a user on MongoDB. So there is no need to parse the username.

Just parse the password then replace it with `<password>` and strip out `test?retryWrites=true&w=majority` from the URI. That should be more than enough.

**Comment by ganeshi4u** [comment]
I have simplified the logic further and got rid of the config variables. This should be working fine by just placing the mongodb uri in the config.

I think you have already removed the part after ` /test? ` in your CI config which resulted in the build failure! i'll add a check or try to handle the exception.

**Comment by ganeshi4u** [comment]
alright test this locally and let me know, am not sure about these CI build errors it seems to be failing to get the uri from config or something. I have everything running as intended on my raspi with these changes.

**Comment by kandnub** [comment]
This is what I had meant by my previous comment. This replaces "\<password\>" or the already provided password with the parsed one and strips out the test part without throwing any errors. Also just import quote_plus instead of urllib.parse. The CI build should pass with this as well.

**config.env**
```
MONGO_DB_PW=
MONGO_DB_URI=
```
**__init.py__**
```
from urllib.parse import quote_plus


MONGO_DB_URI = os.environ.get("MONGO_DB_URI", None)
MONGO_DB_PW = os.environ.get("MONGO_DB_PW", None)

if MONGO_DB_URI:
    MONGO_DB_URI = MONGO_DB_URI.strip("test?retryWrites=true&w=majority")
if MONGO_DB_PW:
    if "<password>" in MONGO_DB_URI:
        MONGO_DB_URI = MONGO_DB_URI.replace("<password>", quote_plus(MONGO_DB_PW), 1)
    else:
        MONGO_DB_URI = MONGO_DB_URI.replace(MONGO_DB_PW, quote_plus(MONGO_DB_PW), 1)
```

**Comment by ganeshi4u** [comment]
@kandnub i have completely got rid the need of any new config variables in the latest force pushed changes. A user can simply copy paste his URI containing the password. Now the code will try to strip the text present in between second `':'` at the beginning and the first available `'@'` from the end of the uri string which gives us the password which will be parsed and is replaced with. The `/test?.....`  part will also be stripped down.

**Comment by kandnub** [comment]
@ganeshi4u, kinda forgot about this but, you can improve the code quite more but these are the things I'd say you could improve. 👍 
```
from urllib.parse import quote_plus # only import quote_plus

MONGO_DB_URI = os.environ.get("MONGO_DB_URI", None)
if MONGO_DB_URI != "":
    try:
        MONGO_DB_URI = MONGO_DB_URI.strip("test?retryWrites=true&w=majority") # this won't throw an error if it's not there, unlike using split.
        MONGO_DB_PASS = MONGO_DB_URI.split(":", 2)[2]
        MONGO_DB_PASS = MONGO_DB_PASS.rsplit("@", 1)[0]
        MONGO_DB_URI = MONGO_DB_URI.replace(MONGO_DB_PASS, quote_plus(MONGO_DB_PASS), 1) # use quote_plus directly instead of having a var just for the parsed password
    except IndexError:
        MONGO_DB_URI = os.environ.get("MONGO_DB_URI", None) # reset the URI just in case
        LOGS.info("Couldn't parse the URI password, using the URI as it is.")
```

**Comment by raphielscape** [comment]
Is this PR stalled already now?

**Pull request closed without merging**
