### PR TITLE
userbot: modules: rewrite gdrive upload

### PR DESCRIPTION
**Pull request by rupansh**
Handling files in memory is faster, improve code where i found it to be cancer. Might add a check for memory idk

### CODE REVIEW

**Comment by rupansh** [comment]
@baalajimaestro merge vro

**Comment by baalajimaestro** [comment]
Well, test what happens if I wanna mirror a 8GB file with just 1GB ram.

**Comment by rupansh** [comment]
> Well, test what happens if I wanna mirror a 8GB file with just 1GB ram.

Pretty sure tg doesn't allow you to upload 8GB file

**Comment by raphielscape** [comment]
> > Well, test what happens if I wanna mirror a 8GB file with just 1GB ram.
> 
> Pretty sure tg doesn't allow you to upload 8GB file

You can make it throw the link instead in case the file size is more than 1 GB

**Comment by rupansh** [comment]
> > > Well, test what happens if I wanna mirror a 8GB file with just 1GB ram.
> > 
> > 
> > Pretty sure tg doesn't allow you to upload 8GB file
> 
> You can make it throw the link instead in case the file size is more than 1 GB

Read the code.
Downloads through urls are done in disk.
Downloads through tg are done in memory with memory checks. It falls back to downloading to disk if enough memory isn't available.

**Pull request merged**
