### PR TITLE
chat.py: Stealth  logging

### PR DESCRIPTION
**Pull request by DrPhilosophus95**
Logs messages stealthily making it appear that the `.log` command doesn't work for those who are not aware of this

### CODE REVIEW

**Comment by zakaryan2004** [comment]
Yeah, but why?

**Comment by DrPhilosophus95** [comment]
Some group admins don't like userbots. So, at least log messages stealthily would  be better. I thought of changing .log command to .logan or any random word or name so that it's even more stealthier.

**Comment by songotenks69** [comment]
@DrPhilosophus95 *cough* *cough* horbis *cough*

**Comment by DrPhilosophus95** [comment]
@songotenks69 What is horbis?

**Comment by baalajimaestro** [comment]
Well, technically, it all lies in your hands to show off you have a userbot and hide it. Its totally upto you, as no one can control the userbot on your account, only you can. 

This PR doesn't make much sense when I have restricted all commands to just outgoing alone. Closing.

**Pull request closed without merging**
