### PR TITLE
Added slaps !!

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
plus a few funny `.hi` and `.shg` strings

### CODE REVIEW

**Comment by zakaryan2004** [comment]
Don't include already merged changes in your PR.

**Comment by baalajimaestro** [comment]
@zakaryan2004 .purge

**Comment by AvinashReddy3108** [comment]
@zakaryan2004 the last one was rejected coz of cancerous memes amd shit..

**Comment by raphielscape** [comment]
Re-PR in a proper history as we do force push, closing this PR

**Comment by raphielscape** [comment]
> @zakaryan2004 the last one was rejected coz of cancerous memes amd shit..

There's ported module that we decided to drop due to clashing license, we can't include that, also too much redudancies

**Pull request closed without merging**
