### PR TITLE
Added SQL Globals

### PR DESCRIPTION
**Pull request by kandnub**
Commit name says what the sql file is about.
Removed spam and NOTIF_OFF vars from init (practically useless?).
notifon and notifoff use sql globals now.

Adding same gvar in DB will delete the older one if it exists before adding the newer one and will delete them with just the var name.
gvarstatus returns the value as string, convert it before using it if it wasn't saved as a string objects.

### CODE REVIEW

**Comment by raphielscape** [comment]
Production Tests?

**Comment by kandnub** [comment]
Wouldn't make a PR if I hadn't tested it, or is it something else you're trying to say? Be more brief.

**Comment by raphielscape** [comment]
> Wouldn't make a PR if I hadn't tested it, or is it something else you're trying to say? Be more brief.

Well, I do asked that because of the bare Exception handling

**Comment by kandnub** [comment]
> > Wouldn't make a PR if I hadn't tested it, or is it something else you're trying to say? Be more brief.
> 
> Well, I do asked that because of the bare Exception handling

Yeah, I should've made it edit the message saying it's running on non-SQL for notif on/off. Rest is fine as it is, as long as there isn't an error related to sql session, which will affect all sql stuff.

**Comment by baalajimaestro** [comment]
@kandnub Nah. No problem. I'll anyways make it all with the mongodb

**Comment by raphielscape** [comment]
Speaking of Mongo, we need to rebase that over to Staging, if Mongo merged to staging, it'll mess up the entire history coz of the merges of the merge

**Comment by baalajimaestro** [comment]
@raphielscape I'll just rename the branch ez

**Comment by songotenks69** [comment]
@baalajimaestro Excuse me what the fuck

**Comment by raphielscape** [comment]
> @raphielscape I'll just rename the branch ez

No, refactor Yacha's stuffs and the inline the history

**Comment by raphielscape** [comment]
I'm not going to expect that merge of merges become merged

**Comment by baalajimaestro** [comment]
@raphielscape F. Will rebase and force push whenever I can.

**Comment by raphielscape** [comment]
> @raphielscape F. Will rebase and force push whenever I can.

Okay

**Pull request merged**
