### PR TITLE
[Memes] Removed the "Hi" that edited the message to "Hoi!😄"

### PR DESCRIPTION
**Pull request by peaktogoo**
This is annoying af.

### CODE REVIEW

**Comment by songotenks69** [comment]
@peaktogoo 10/10 agree

**Comment by zakaryan2004** [comment]
+1

**Comment by peaktogoo** [comment]
@zakaryan2004 Request btw

**Comment by peaktogoo** [comment]
Still, as @baalajimaestro stated in Telegram group, https://t.me/c/1372533112/256409 saying No, I still gonna keep this PR opening lmao

**Comment by baalajimaestro** [comment]
@peaktogoo I won't remove, as I said earlier, I will add a default disable flag to disable it. That part of code won't be removed.

**Pull request closed without merging**
