### PR TITLE
userbot: modules: add gbans/fbans

### PR DESCRIPTION
**Pull request by rupansh**
BBOTS format -
{"@botusername1" : ["success string1", "success string2"]}
FGROUPS format-
["@groupuser1", "@groupuser2"]

Signed-off-by: rupansh <rupanshsekar@hotmail.com>

To be tested and extended by baalajimaestro

### CODE REVIEW

**Comment by rupansh** [comment]
> Chnages approved. But hol' up. I'll manually run and test it

wah yr 
image

**Comment by rupansh** [comment]
trash pr cuz i pushed my refactor meme lol

**Comment by baalajimaestro** [comment]
This will remind me to work on this. Nu close thx

**Comment by rupansh** [comment]
> This will remind me to work on this. Nu close thx

Ree my code got delet

**Comment by baalajimaestro** [comment]
@rupansh F.

**Comment by raphielscape** [comment]
Can I stall this now? xd

**Comment by rupansh** [comment]
bruh moment

**Comment by gotenksIN** [comment]
__bruh__

**Comment by baalajimaestro** [comment]
Done under commit https://github.com/raphielgang/telegram-userbot/commit/a0cddeddab93a28358d460acf0b8ff558256788c

**Pull request closed without merging**
