### PR TITLE
modules: welcome_mute: cleanups, extend the algorith, fix bugs

### PR DESCRIPTION
**Pull request by zakaryan2004**
* Cleaned up the code(from pylint -8.5 score to 9.56)
* Fixed up some bugs such as using loop variable outside the loop
* Remove unnecessary imports
* Extend the algorithm by adding Announcements Bot name to the list
* Add helper to the module
* Fix the logger logic(the module now checks if logger is enabled or not)

Signed-off-by: Gegham Zakaryan <zakaryan.2004@outlook.com>

### CODE REVIEW

**Comment by baalajimaestro** [comment]
@zakaryan2004 K.

**Comment by raphielscape** [comment]
Seems good for me, testing needed

**Comment by zakaryan2004** [comment]
@raphielscape At least it will work better than the current code in staging. The only part I suppose MAY need to be tested is the errors part as I removed the error imports. I remember that there were some problems in Telethon, but I don't think it will happen this time.

**Comment by raphielscape** [comment]
There's sometimes a exception loop happen coz of Telegram API do "stuffs"

Need testing then

**Comment by baalajimaestro** [comment]
@zakaryan2004 Tag when i can merge

**Comment by zakaryan2004** [comment]
Made it much better, but still some testing needed

**Comment by baalajimaestro** [comment]
Okay....

**Comment by zakaryan2004** [comment]
@baalajimaestro @raphielscape merge now reee

**Pull request merged**
