### PR TITLE
refactor memes

### PR DESCRIPTION
**Pull request by rupansh**
Better and much efficient code.

reference taken from nim-tg-manager's improvement- https://github.com/rupansh/nim-tg-manager/blob/master/src/tg_managerpkg/memes.nim

### CODE REVIEW

**Comment by rupansh** [comment]
@raphielscape @baalajimaestro hit the merge button

**Comment by songotenks69** [comment]
Can I got the merge button?

**Comment by songotenks69** [comment]
I can hit the merge button

**Comment by rupansh** [comment]
> I can hit the merge button

do eet

**Pull request merged**
