### PR TITLE
userbot: modules: add rule34 image fetch

### PR DESCRIPTION
**Pull request by rupansh**
thx me later dude

Signed-off-by: rupansh <rupanshsekar@hotmail.com>

### CODE REVIEW

**Comment by baalajimaestro** [comment]
Will stall this until staging is fixed up

**Comment by raphielscape** [comment]
Propose for a NSFW Toggle based on my submission on Paperplane chat, we can stall this until Staging and the NSFW Toggle is done

**Comment by rupansh** [comment]
sneak

**Comment by baalajimaestro** [comment]
Force pushed to remove sdfaa

**Comment by rupansh** [comment]
@raphielscape merge when yaar

**Comment by raphielscape** [comment]
Later xd

**Comment by baalajimaestro** [comment]
Pecking conflicts, pull and re-pr

**Comment by rupansh** [comment]
Data khatam kek

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MrYacha** [comment]
This PR is completely garbage, also GitHub isn't a chat, so stop doing it.
Closing PR.

**Comment by rupansh** [comment]
@MrYacha The PR is garbage because a certain someone force pushed this repo :^)

**Comment by raphielscape** [comment]
I'll pull this separately and merge later

**Comment by rupansh** [comment]
> I'll pull this separately and merge later

okaye

**Pull request closed without merging**
