### PR TITLE
Some visual fixes + fix for .sd feature

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
Learnt to make many changes in a single commit , yay !!
No more unnecessary  staging CI builds.

### CODE REVIEW

**Comment by zakaryan2004** [comment]
We don't need "potential" fixes. Test it and see if it's fixed or not.

**Comment by AvinashReddy3108** [comment]
> We don't need "potential" fixes. Test it and see if it's fixed or not.

let me try these fixes on a fork and will let you know if it's good to merge.

**Comment by AvinashReddy3108** [comment]
> We don't need "potential" fixes. Test it and see if it's fixed or not.

It works !!

.sd 99 Self Destruct Message

**Comment by AvinashReddy3108** [comment]
Please ignore this mess I made, I'm a newbie at git stuff..

**Comment by raphielscape** [comment]
You can make a new branch for pull request reviews so your changes that doesn't intended to be in Pull Request doesn't being included

**Pull request closed without merging**
