### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by jcs004**

### CODE REVIEW

**Comment by ATechnoHazard** [comment]
@jcs004 Wau

**Comment by whoknowswhoiam** [comment]
@ATechnoHazard nerd

**Comment by ATechnoHazard** [comment]
Are you fucking dumb

**Comment by baalajimaestro** [comment]
@whoknowswhoiam > Key leak

**Comment by ATechnoHazard** [comment]
@ATechnoHazard ^

**Comment by whoknowswhoiam** [comment]
> @whoknowswhoiam > Key leak

wut

**Comment by songotenks69** [comment]
Bruh wtf

**Comment by Yash-Garg** [comment]
Real genius, wow !

**Comment by Jeepeo** [comment]
lmao

**Pull request closed without merging**
